### ISSUE TITLE
consultar turnos

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#1]
[más info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/consulta-de-turnos)

**Comment by estebanlanik** [comment]
Buscar turno no funciona correctamente, al ingresar el dni , no traer todos los valores correspondientes

**Comment by estebanlanik** [comment]
Nombre permite numeros
telefono permite caracteres
email no valida mail valido
