### ISSUE TITLE
editar cliente

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#11]
[más info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-registrador-de-cliente-puedo-editar-los-datos-del-cliente)

**Comment by CristianGonzalez360** [comment]
Funcionando sin validación pero no puedo pushear

**Comment by redvladimirogaston** [comment]
Ya puse para testear registrar cliente & registrar vehiculo & registrar orden de trabajo. Voy a mezclar tu código de editar cliente con el que subí a develop luego de la mezcla con la issue#3.

**Comment by redvladimirogaston** [comment]
Cristian dame una mano con editar cliente. Lo rompí sin querer, había muchos conflictos y tuve que optar.

**Comment by CristianGonzalez360** [comment]
Dale ahora me fijo
