### ISSUE TITLE
login

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#12]
[más info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-Logger-puedo-autenticarme-en-el-sistema)

**Comment by estebanlanik** [comment]
no lo podemos testear con los usuarios de prueba que estamos usando ahora, ya que no son mails validos

**Comment by estebanlanik** [comment]
permite el ingreso de cualquier formato de usuario, y no solo email

**Comment by estebanlanik** [comment]
la clave deberia estar encliptada
