### ISSUE TITLE
registrar vehículo

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#3]
[más info](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-supervisor-puedo-registrar-veh%C3%ADculo-durante-el-proceso-de-alta-de-cliente)

**Comment by estebanlanik** [comment]
El boton registrar nuevo vehiculo no funciona

**Comment by estebanlanik** [comment]
Color y combustion permiten valores numericos
