### ISSUE TITLE
Como Supervisor puedo registrar la entrega de vehículo de taller

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#30]
[mas info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-Supervisor-puedo-registrar-la-entrega-de-veh%C3%ADculo-de-taller)

**Comment by redvladimirogaston** [comment]
Consulta sobre la issue#30 --> se rechazan los presupuestos del cliente por lo tanto en registrar entrega de vehículo debería aparecer los datos del vehículo a entregar sin embargo no me aparece nada

**Comment by pabloabregu** [comment]
Solucionado!
