### ISSUE TITLE
Como gerente puedo registrar pedido unidad.

### ISSUE THREAD

**Issue by JereMedr** [redvladimirogaston/ProyectoConcesionario#41]
[mas info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-gerente-puedo-registrar-pedido-unidad)

**Comment by pabloabregu** [comment]
**Q1 - bug critic:**

**ENTRADA**: Se selecciona la venta y se solicita Registrar Pedido
**SALIDA**: ConstraintViolationException: La columna "IDUSUINGRESO" no permite valores nulos (NULL)

**ESPERADO**: Se debería registrar el pedido
