### ISSUE TITLE
Como supervisor puedo consultar ordenes de trabajo

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#5]
[más info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-Supervisor-puedo-consultar-ordenes-de-trabajo)

**Comment by redvladimirogaston** [comment]
Necesitas ayuda con la pantalla?

**Comment by JereMedr** [comment]
No funciona en rama develop, solo en branch issue#8
