### ISSUE TITLE
registrar turno

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#6]
[más info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-Supervisor-puedo-registrar-turnos)

**Comment by estebanlanik** [comment]
Al completar los campos,no permite guardar el turno

**Comment by estebanlanik** [comment]
Nombre permite numeros
Telefono permite caracteres
Mail no valida el formato de mail correcto
