### ISSUE TITLE
registrar cliente

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#7]
[más info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-registrador-registrador-de-cliente-quiero-registrar-un-cliente.)

**Comment by estebanlanik** [comment]
![image](https://user-images.githubusercontent.com/57278588/98310667-58d32280-1fac-11eb-887d-7959721966ea.png)
 mensaje de validacion duplicado, falta validacion de depto

**Comment by JereMedr** [comment]
Al registrar cliente no soporta que en la calle y localidad se ponga un input con espacios ej: "9 de Julio" 
![image](https://user-images.githubusercontent.com/24230341/99024323-1928af80-2545-11eb-8229-6789349b97a4.png)

**Comment by CristianGonzalez360** [comment]
Listo, arreglado.
