### ISSUE TITLE
registrar presupuesto ot

### ISSUE THREAD

**Issue by pabloabregu** [redvladimirogaston/ProyectoConcesionario#8]
[más info.](https://github.com/redvladimirogaston/ProyectoConcesionario/wiki/Como-t%C3%A9cnico-puedo-registrar-presupuesto)

**Comment by CristianGonzalez360** [comment]
@redvladimirogaston tengo problemas para guardar. guardo el presupuesto, pero no se como obtener el id para setearselo a repuestoPlanificado y trabajoPlanificado ya que presupuesto no tiene ningún dato único como para hacer la consulta por ese criterio.

**Comment by redvladimirogaston** [comment]
Es probable que esté mal el modelo de la base de datos. Ahora lo reviso.

**Comment by redvladimirogaston** [comment]
Tenés la orden de trabajo para poder llegar al presupuesto!

**Comment by CristianGonzalez360** [comment]
Si la relación fuera 1 a 1 si
